spring:
    application:
        name: meters-readings
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: false
        database: postgresql
        properties:
            hibernate:
                generate_statistics: false
            jdbc:
                batch_size: 100
                order_inserts: true
                order_updates: true
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
        password: ${DB_PWD:root4905}
        username: ${DB_USER:postgres}
        driver-class-name: org.postgresql.Driver
        hikari:
            schema: registration_users
    jackson:
        default-property-inclusion: non_null
    flyway:
        baseline-on-migrate: true
        locations: classpath:db/migration
        schemas: registration_users
server:
    port: 8082

